name: Actions Workflow

on: 
    repository_dispatch:
        types: [test]
    # pull_request:
    #   types: [closed]

jobs:
    run-github-actions:
        runs-on: ubuntu-20.04
        steps:
            - name: List Files Before Checkout action
              run: |
                pwd
                ls -a
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
                echo "${{ github.token }}"
                # git clone git@github:$GITHUB_REPOSITORY

            - name: Run Checkout action
              uses: actions/checkout@v2
            
            - name: List Files After Checkout action
              run: |
                pwd 
                ls -la
            
            - name: Simple JS Action
              id: greet
              uses: actions/hello-world-javascript-action@v1 # or you can use a commit id to reference an action
              with:
                  who-to-greet: Jose

            - name: Log Greeting Time
              run: echo "${{ steps.greet.outputs.time }}"
